kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: contrail-operator
subjects:
- kind: ServiceAccount
  name: contrail-operator
roleRef:
  kind: Role
  name: contrail-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: contrail-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - contrail-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - contrail-operators.juniper.net
  resources:
  - '*'
  - configdbs
  - confignodes
  - controlnodes
  - analyticsdbs
  - analyticsnodes
  - webuis
  - infravars
  - kubemanagers
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contrail-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contrail-kube-manager
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: contrail-kube-manager
subjects:
- kind: ServiceAccount
  name: contrail-kube-manager
roleRef:
  kind: ClusterRole
  name: contrail-kube-manager
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: contrail-kube-manager
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - '*'
  verbs:
  - '*'
