apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: infravars.contrail-operators.juniper.net
spec:
  group: contrail-operators.juniper.net
  names:
    kind: InfraVars
    listKind: InfraVarsList
    plural: infravars
    singular: infravars
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: contrail-kube-manager
  namespace: kube-system
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contrail-kube-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: contrail-kube-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contrail-kube-manager
subjects:
- kind: ServiceAccount
  name: contrail-kube-manager
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: contrail-kube-manager-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: contrail-kube-manager
type: kubernetes.io/service-account-token
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: contrail-operator
subjects:
- kind: ServiceAccount
  name: contrail-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: contrail-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: contrail-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - nodes/status
  - nodes/spec
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - contrail-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - contrail-operators.juniper.net
  resources:
  - configdbs
  - confignodes
  - controlnodes
  - analyticsdbs
  - analyticsnodes
  - webuis
  - infravars
  - kubemanagers
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contrail-operator
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contrail-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: contrail-operator
  template:
    metadata:
      labels:
        name: contrail-operator
    spec:
      serviceAccountName: contrail-operator
      hostNetwork: true
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node.kubernetes.io/not-ready
        operator: Exists
        effect: NoSchedule
      containers:
        - name: contrail-operator
          # Replace this with the built image name
          image: "pvijayaragav/operator_test:k8s_latest"
          command:
          - contrail-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
#              value: ""
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "contrail-operator"

---
apiVersion: contrail-operators.juniper.net/v1alpha1
kind: InfraVars
metadata:
  name: example-infravars
spec:
#  contrailMasters: "10.84.13.57"
#  apiServer: "10.84.13.57"
#  contrail_registry: "ci-repo.englab.juniper.net:5010"
#  contrail_tag: ":rhel-queens-5.1-54"
  contrail_registry: "opencontrailnightly"
  contrail_tag: ":latest"
